hostname=ep-orange-cherry-aqe3dr70-pooler.c-8.us-east-1.aws.neon.tech
port=5432
database=neondb
username=neondb_owner
password=npg_P5fR1KgTdazU
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


